[project]
name = "woodenfis-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alibabacloud-dysmsapi20170525>=4.1.2",
    "fastapi>=0.116.1",
    "fastmcp>=2.10.5",
    "jwt>=1.4.0",
    "sqlalchemy>=2.0.41",
]
